[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://ai-invoice-2f1n.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://ai-invoice-2f1n.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://ai-invoice-2f1n.onrender.com"
